### ISSUE TITLE
Implement Github Team Membership

### ISSUE THREAD

**Issue by johnrengelman** [improving-minnesota/terraform#2]
- [ ] Implement resource: https://github.com/objectpartners/terraform/blob/f-github-provider/builtin/providers/github/resource_github_team_membership.go
- [ ] Add acceptance tests

**Comment by JacobASeverson** [comment]
https://github.com/objectpartners/terraform/pull/9 takes care of this and is ready for review

**Comment by johnrengelman** [comment]
Closed with https://github.com/objectpartners/terraform/commit/2fb76e9524132521e34478ce409d66931400975f
