### ISSUE TITLE
Implement Github Team Repository

### ISSUE THREAD

**Issue by johnrengelman** [improving-minnesota/terraform#3]
- [ ] Implement resource: https://github.com/objectpartners/terraform/blob/f-github-provider/builtin/providers/github/resource_github_team_repository.go
- [ ] Add acceptance tests

**Comment by JacobASeverson** [comment]
Implemented by #10

**Comment by johnrengelman** [comment]
Closed with https://github.com/objectpartners/terraform/commit/2fb76e9524132521e34478ce409d66931400975f
